services:
  avr:
    image: avr_build:0.0.1
    user: ${USERID}:${GROUPID}
    container_name: avr
    volumes:
      - ${PWD}:/usr/app/
    # Pour bash
    stdin_open: true
    tty: true

  build:
    extends: avr
    container_name: avr_build
    command:
      - /bin/sh
      - -c
      - |
        make all

  clean:
    extends: avr
    container_name: avr_clean
    command:
      - /bin/sh
      - -c
      - | 
        make clean

  cleanall:
    extends: avr
    container_name: avr_cleanall
    command:
      - /bin/sh
      - -c
      - | 
        make distclean

  custom:
    extends: avr
    container_name: avr_custom
    command:
      - /bin/sh
      - -c
      - | 
        make ${CUSTOM_CMD}

  install:
    extends: avr
    container_name: avr_install
    command: ./flash_arduino.sh
